// AUTO-GENERATED mapping from Navrist_Qualitative_Best_Graph_Each_Metric.xlsx

export function normalizeMetricTitle(title) {
  if (!title) return '';
  return title.trim().toLowerCase().replace(/\s+/g, ' ');
}

export const QUAL_CHART_MAPPING = {
  'past successes / failures': "comparison_bar",
  'management tenure': "horizontal_bar",
  'relevance to current strategy': "progress",
  'pay structure': "stacked_100",
  'equity ownership': "progress",
  'vesting structure': "stacked_100",
  'long-term orientation': "rating_5",
  'leadership depth': "horizontal_bar",
  'succession readiness': "binary",
  'key executive dependency': "risk_bar",
  'transparency in disclosures': "rating_5",
  'openness in investor communication': "rating_5",
  'delivered vs stated milestones': "comparison_bar",
  'capital allocation execution': "comparison_bar",
  'strategic execution consistency': "timeline",
  'innovation focus': "rating_5",
  'compliance orientation': "rating_5",
  'employee morale': "rating_5",
  'attrition evidence': "line",
  'control levels': "stacked_100",
  'changes over time': "line",
  'direction (buying / selling)': "diverging_directional",
  'presence of pledging': "binary",
  'size of pledged shares': "progress",
  'trend in pledging': "line",
  'margin-call risk': "risk_rating_5",
  'frequency of rpts': "bar_time",
  'counterparty identity': "comparison_bar",
  'disclosure quality of rpts': "rating_5",
  'off-balance-sheet vehicles': "evidence_bar",
  'special purpose vehicles (spvs)': "horizontal_bar",
  'subsidiaries abroad': "ranked_bar",
  'complexity / transparency of group structure': "risk_rating_5",
  'independent directors’ quality': "rating_5",
  'audit committee activity': "bar_time",
  'nomination & remuneration committee activity': "bar_time",
  'board attendance and committee participation': "comparison_bar",
  'auditor tenure': "timeline",
  'auditor switches': "timeline",
  'qualifications in audit reports': "binary_audit",
  'reservations / emphasis of matter': "timeline",
  'capital expenditure (capex)': "line",
  'acquisitions': "bar_time",
  'buybacks': "timeline",
  'dividends': "line",
  'capital allocation rationale': "stacked_100",
  'disclosure quality': "rating_5",
  'minority shareholder voting and treatment': "stacked_100",
  'disclosure consistency and timeliness': "timeline",
  'frequency of insider selling': "bar_time",
  'timing of insider selling': "timeline",
  'size of insider selling': "horizontal_bar",
  'rationale for insider selling': "evidence_bar",
  'frequency of insider buying': "bar_time",
  'size of insider buying': "horizontal_bar",
  'repeat buying / conviction pattern': "timeline",
  'placements / preferential allotments': "timeline",
  'dilution to existing shareholders': "progress",
  'pricing / discount and rationale': "comparison_bar",
  'lock-in expiry date': "timeline",
  'potential sellable block size': "progress",
  'promoter/company loan direction': "diverging_directional",
  'interest rate and terms': "comparison_bar",
  'outstanding balance / concentration': "ranked_bar",
  'pledge release / unwinding': "line",
  'forced-sale / invocation signals': "timeline",
  'related-party payment frequency': "bar_time",
  'payment rationale / arm’s-length basis': "evidence_bar",
  'top customer revenue concentration': "ranked_bar",
  'customer dependency': "risk_rating_5",
  'supplier concentration': "ranked_bar",
  'supplier terms / dependence': "risk_rating_5",
  'receivables growth': "line",
  'receivables aging / overdue quality': "stacked_100",
  'revenue-recognition disclosure risk': "risk_rating_5",
  'inventory trend': "line",
  'inventory vs demand': "diverging_bar",
  'obsolete / slow-moving inventory': "progress",
  'off-market transactions': "evidence_bar",
  'non-arm’s-length contracts': "risk_rating_5",
  'accounting policy changes': "timeline",
  'changes in accounting estimates': "timeline",
  'one-off adjustments / special items': "bar_time",
  'earnings smoothing signals': "line",
  'number of material competitors': "horizontal_bar",
  'relative market position': "ranked_bar",
  'competitor strength': "rating_5",
  'entry barriers': "risk_rating_5",
  'price-war evidence': "line",
  'regulatory barriers': "risk_rating_5",
  'trade barriers': "risk_rating_5",
  'foreign competitor presence': "binary",
  'import competition': "risk_rating_5",
  'switching costs': "rating_5",
  'network effects': "rating_5",
  'channel mix': "stacked_100",
  'channel control': "rating_5",
  'group-channel overlap': "binary_risk",
  'contract duration / renewal': "comparison_bar",
  'customer churn / retention': "line",
  'distribution reach': "ranked_bar",
  'peer distribution advantage': "comparison_bar",
  'patent / trademark expiry': "timeline",
  'r&d pipeline depth': "pipeline",
  'legacy technology dependence': "risk_rating_5",
  'cybersecurity posture': "risk_rating_5",
  'third-party technology dependence': "risk_rating_5",
  'license continuity risk': "timeline",
  'single-source suppliers': "risk_progress",
  'geographic concentration / china exposure': "ranked_bar",
  'inventory buffers': "progress",
  'capacity vs demand': "comparison_bar",
  'capital constraints to scale': "risk_rating_5",
  'price protection clauses': "binary",
  'currency clauses': "stacked_100",
  'lead time / throughput': "line",
  'quality defects / warranty claims': "line",
  'renewal burden': "risk_progress",
  'litigation count and materiality': "bar_time",
  'probability / management assessment': "risk_rating_5",
  'competition investigations': "timeline",
  'potential financial / operational impact': "horizontal_bar",
  'tax disputes': "bar_time",
  'historic tax exposures': "bar_time",
  'ongoing tax audits / assessments': "timeline",
  'subsidy dependence': "progress",
  'environmental regulation exposure': "risk_rating_5",
  'commodity input dependence': "risk_rating_5",
  'export/import dependence': "stacked_100",
  'geopolitical trade risk': "risk_rating_5",
  'interest-rate sensitivity': "risk_progress",
  'economic cyclicality': "risk_rating_5",
  'hedging protection': "progress",
  'leverage policy': "line",
  'covenant management': "progress",
  'refinancing history': "timeline",
  'covenant breaches / remedies': "timeline",
  'dividend consistency': "line",
  'rationale for changes': "evidence_bar",
  'lease commitments': "comparison_bar",
  'structured / off-balance-sheet arrangements': "binary_risk",
  'm&a frequency': "bar_time",
  'acquisitive vs disciplined pattern': "evidence_bar",
  'related-party acquisitions': "binary_risk",
  'assets sold to affiliates': "binary_risk",
  'm&a pipeline': "pipeline",
  'value-creation rationale': "rating_5",
  'esg targets': "progress",
  'community impact': "rating_5",
  'displacement / resettlement': "binary_risk",
  'pollution / environmental incidents': "line",
  'hazardous waste': "line",
  'pending clearances': "evidence_bar",
  'union / collective bargaining exposure': "binary_risk",
  'strikes / disputes': "line",
  'employee grievances': "line",
  'human-rights policy / supplier screening': "binary",
  'forced/child labour incidents': "timeline",
  'material controversies': "timeline",
  'stakeholder complaints': "line",
  'safety incidents': "line",
  'negative campaigns / reputation response': "timeline",
  'regulatory fines': "bar_time",
  'public investigations': "timeline",
  'disclosure detail': "rating_5",
  'timeliness / frequency': "line",
  'rpt completeness': "rating_5",
  'rpt explanation quality': "rating_5",
  'audit opinion': "binary_audit",
  'emphasis of matter / key audit matters': "timeline",
  'restatements': "timeline",
  'financial statement complexity': "risk_rating_5",
  'multiple currencies': "horizontal_bar",
  'subsidiary complexity': "horizontal_bar",
  'cfo / finance leadership churn': "timeline",
  'group structure opacity': "risk_rating_5",
  'dormant / non-operating entities': "single_value",
  'year-end transaction concentration': "bar_monthly",
  'explanation quality': "rating_5",
  'sudden departures': "timeline",
  'succession response': "binary",
  'rapid insider selling': "bar_time",
  'concentrated block sales': "stacked_100",
  'capital raise frequency': "bar_time",
  'discount / pricing': "comparison_bar",
  'one-off transaction frequency': "bar_time",
  'transfer pricing / rationale': "evidence_bar",
  'auditor resignation': "timeline",
  'internal control issues': "risk_rating_5",
  'response cadence': "timeline",
  'substance of response': "evidence_bar",
  'asset quality': "binary_applicable",
  'related-party exposures': "binary_applicable",
  'regulatory capital': "binary_applicable",
  'loan underwriting quality': "binary_applicable",
  'patent cliffs': "binary_applicable",
  'regulatory inspections': "binary_applicable",
  'price controls': "binary_applicable",
  'model refresh cycle': "binary_applicable",
  'channel inventory': "binary_applicable",
  'export dependency': "binary_applicable",
  'client concentration': "binary_applicable",
  'contract renewal risk': "binary_applicable",
  'visa / immigration dependence': "binary_applicable",
  'brand strength': "binary_applicable",
  'distribution depth': "binary_applicable",
  'commodity input volatility': "binary_applicable",
  'sanctions / embargo exposure': "binary_risk",
  'tariff exposure': "risk_rating_5",
  'gst sensitivity': "risk_rating_5",
  'import duty sensitivity': "risk_rating_5",
  'convertibility risk': "risk_rating_5",
  'repatriation risk': "risk_rating_5",
  'top management-identified risk': "ranked_bar",
  'capital allocation framework': "stacked_100",
  'management-named competitors': "ranked_bar",
  'revenue sensitivity': "ranked_bar",
  'margin sensitivity': "ranked_bar",
  'management explanation of material rpts': "evidence_bar",
  'ceo succession': "binary",
  'cfo succession': "binary",
};
