"""Snapshot of what documents exist in the manual-upload workflow and what was actually verified for each company-year.

    python tests/manual_upload_inventory.py --out docs/manual_upload_inventory_2026-10.md

Documents are only listed, never moved or deleted."""
import argparse
import collections
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _ls(*p):
    d = os.path.join(ROOT, *p)
    return sorted(os.listdir(d)) if os.path.isdir(d) else []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "manual_upload_inventory_2026-10.md"))
    a = ap.parse_args()
    L = ["# Manual-upload workflow - document inventory and verification coverage (snapshot)", "",
         "Generated by `tests/manual_upload_inventory.py`. Source documents are preserved; nothing here moves or deletes them.", ""]
    L += ["## Raw uploads (`uploads/<SYMBOL>/`)", "", "| Symbol | Files | PDF | XML/XBRL | HTML |", "|---|---|---|---|---|"]
    for sym in _ls("uploads"):
        fs = _ls("uploads", sym)
        ext = collections.Counter(os.path.splitext(f)[1].lower() for f in fs)
        L.append(f"| {sym} | {len(fs)} | {ext.get('.pdf', 0)} | {ext.get('.xml', 0)} | {ext.get('.html', 0)} |")
    ar = collections.defaultdict(list)
    for f in _ls("cache", "ar_text"):
        m = re.fullmatch(r"([A-Z0-9&-]+)_(\d{4})\.json", f)
        if m:
            ar[m.group(1)].append(int(m.group(2)))
    pdfs = collections.defaultdict(list)
    for f in _ls("cache", "ar_pdfs"):
        m = re.fullmatch(r"([A-Z0-9&-]+)_(\d{4})\.pdf", f)
        if m:
            pdfs[m.group(1)].append(int(m.group(2)))
    L += ["", "## Annual reports available to the pipeline", "",
          f"* Parsed-text cache (`cache/ar_text`, the manual workflow's page store): {sum(len(v) for v in ar.values())} company-years / {len(ar)} companies.",
          f"* Cached PDFs (`cache/ar_pdfs`): {sum(len(v) for v in pdfs.values())} company-years / {len(pdfs)} companies.",
          f"* XBRL (`cache/xbrl_manual`): {', '.join(_ls('cache', 'xbrl_manual')) or '-'}.",
          f"* Shareholding (`cache/shareholding_manual`): {', '.join(_ls('cache', 'shareholding_manual')) or '-'}.", "",
          "| Company | Parsed-text years | Cached PDF years |", "|---|---|---|"]
    for sym in sorted(ar):
        L.append(f"| {sym} | {', '.join(map(str, sorted(ar[sym])))} | {', '.join(map(str, sorted(pdfs.get(sym, [])))) or '-'} |")
    sv = json.load(open(os.path.join(ROOT, "docs", "source_verification_2026-10.json"), encoding="utf-8"))
    L += ["", "## Company-years checked against the filing", "",
          "*Lineage* = base facts found printed in the filing (of 28); *publisher* = revenue (net sales), whole-entity profit, tax %, borrowings vs Screener "
          "(annual, consolidated). **ANURAS FY2026 is the only company-year with all 68 ratios traced to page level.** Nothing below is labelled fully verified.", "",
          "| Company-year | Basis | Lineage | Publisher agreement (revenue / profit / tax / debt) |", "|---|---|---|---|"]
    for cy, v in sorted(sv.items()):
        if v.get("error"):
            L.append(f"| {cy} | - | - | extraction failed |")
            continue
        p = v["publisher"]
        mk = lambda k: "agree" if p[k]["agrees"] else "differs (documented)"          # noqa: E731
        L.append(f"| {cy} | {v['basis']} | {v['lineage_found']}/28 | {mk('revenue')} / {mk('net_profit_whole_entity')} / {mk('tax_pct')} / {mk('debt_vs_borrowings')} |")
    L += ["", "## Bank filings run through the manual workflow (RBI-format statements, identity-gated)", "",
          "HDFCBANK, ICICIBANK, KOTAKBANK and SBIN (latest cached year): NIM, CASA (not for SBIN: split not disclosed in the statements), gross / net NPA, provision "
          "coverage, capital adequacy, credit-to-deposit and cost-to-income computed after the manual-upload fix (previously all unavailable). "
          "Values are identity-checked; they are not individually matched against a second publisher.", ""]
    open(a.out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
