"""
Universal qualitative task engine (Phase 3C).

    registry -> source router -> evidence extraction -> EvidenceBundle
    -> interpretation -> scoring -> QualitativeResult -> persistence

The single execution path `evaluate_task()` is what the API, the batch
worker, and (where a task's evidence contract is already migrated) the
manual-upload pipeline all call - never three independent implementations.

Reuses, never re-implements:
  - `tools.qualitative_task_registry.TASK_BY_ID` (Phase 3B's extended
    364-entry registry - read-only, never regenerated by this module).
  - `tools.qualitative_source_router` / `tools.qualitative_evidence_extraction`
    (Phase 3B's evidence foundation).
  - `tools.qualitative_db.write_qualitative`/`read_qualitative` (the
    existing, sole persistence choke point - no second persistence system).
  - `tools.qualitative_engine._manual_doc_uploaded` (the existing, working
    manual-mode document-availability check - not duplicated).

Company-agnostic by construction: every function takes
(symbol, name, fiscal_year, task_id, ...) - no company/filename/page-number
branch anywhere in this file (enforced by
tests/test_qualitative_task_engine.py's static guard).
"""

import hashlib
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from tools.qualitative_evidence import (
    Confidence, ConfidenceTier, EvidenceBundle, EvidenceStatus, QualitativeEvidence,
    QUALITATIVE_EXTRACTION_VERSION,
)
from tools.qualitative_evidence_extraction import (
    extract_text_based_evidence, extract_board_composition, extract_promoter_ownership,
    extract_insider_activity, extract_segment_concentration, STRUCTURED_PRIMITIVES, TEXT_BASED_CONCEPTS,
)
from tools.qualitative_source_router import resolve_availability
from tools.qualitative_task_registry import TASK_BY_ID
from tools.qualitative_db import write_qualitative, read_qualitative

# Bumped whenever this engine's interpretation/scoring/aggregation logic
# changes in a way that could change a previously-persisted result -
# distinct from `QUALITATIVE_EXTRACTION_VERSION` (which tracks the
# evidence-extraction layer) and from `qualitative_db._QUALITATIVE_LOGIC_VERSION`
# (the legacy compute_fn layer's own version, which every write already
# goes through regardless of origin). Stored inside the payload (no DB
# schema change) as `_engine_version`.
QUALITATIVE_ENGINE_VERSION = 1

# Marks a payload as written by THIS engine (vs. a legacy compute_fn), so a
# cache read can tell the two apart even though they share one table/one
# global `_logic_version` gate.
_ENGINE_MARKER = "qualitative_task_engine"

# Source types this engine always attempts, regardless of manual/automatic
# mode - the 4 live-scraper-backed sources (never upload-dependent) plus
# the Annual Report itself (the automatic pipeline's baseline).
_ALWAYS_ATTEMPTED_SOURCES = {
    "annual_report", "quarterly_corporate_governance_filing",
    "shareholding_pattern_filing", "insider_trading_disclosures", "credit_rating_report",
}

_STRUCTURED_EXTRACTORS = {
    "extract_board_composition": extract_board_composition,
    "extract_promoter_ownership": extract_promoter_ownership,
    "extract_insider_activity": extract_insider_activity,
    "extract_segment_concentration": extract_segment_concentration,
}

_CONCEPT_SOURCE_TYPE = {
    "extract_board_composition": "quarterly_corporate_governance_filing",
    "extract_promoter_ownership": "shareholding_pattern_filing",
    "extract_insider_activity": "insider_trading_disclosures",
    "extract_segment_concentration": "annual_report",
}


@dataclass(frozen=True)
class QualitativeResult:
    company_identity: str
    fiscal_year: Optional[int]
    task_key: str                      # parent/section-level id, e.g. "A.1"
    subtask_key: str                   # the evaluated registry task_id, e.g. "A.1.A"
    score: Optional[Any]
    score_scale: Optional[str]
    status: EvidenceStatus
    confidence: Confidence
    interpretation: str
    evidence: List[QualitativeEvidence] = field(default_factory=list)
    provenance: List[Dict] = field(default_factory=list)
    visualization_metadata: Optional[Dict] = None
    extraction_version: int = QUALITATIVE_EXTRACTION_VERSION
    qualitative_logic_version: int = QUALITATIVE_ENGINE_VERSION
    document_set_version: Optional[str] = None
    from_cache: bool = False

    def to_payload(self) -> Dict:
        """Serializes to the SAME jsonb payload shape `qualitative_db`
        already persists (subpoint_id/title/rationale/pathway_results),
        so existing frontend consumers of `/api/v1/qualitative/{symbol}`
        keep working unchanged, plus the new structured fields alongside."""
        return {
            "_engine": _ENGINE_MARKER,
            "_engine_version": self.qualitative_logic_version,
            "_extraction_version": self.extraction_version,
            "_document_set_version": self.document_set_version,
            "subpoint_id": self.subtask_key,
            "task_key": self.task_key,
            "available": self.status not in (EvidenceStatus.NOT_DISCLOSED, EvidenceStatus.INSUFFICIENT_EVIDENCE,
                                              EvidenceStatus.NOT_APPLICABLE, EvidenceStatus.ERROR),
            "score": self.score,
            "score_scale": self.score_scale,
            "status": self.status.value,
            "confidence_tier": self.confidence.tier.value,
            "confidence_score": self.confidence.score,
            "confidence_reason": self.confidence.reason,
            "rationale": self.interpretation,
            "provenance": self.provenance,
            "visualization_metadata": self.visualization_metadata,
            "pathway_results": [
                {"source": p["source_document_type"], "result": "CHECKED", "note": p.get("extracted_text")}
                for p in self.provenance
            ],
        }


def _visualization_metadata(task_row: Dict, status: EvidenceStatus) -> Dict:
    """Parses the registry's own `visualization_rule` string (e.g. 'Donut
    chart: ... | Colors: Positive=Green, ...') into structured metadata -
    never computes a NEW visualization rule, only structures the existing
    one. Generic string parsing, not per-task."""
    raw = task_row.get("visualization_rule") or ""
    chart_type = None
    if raw:
        chart_type = raw.split(":", 1)[0].strip() or None
    colors = {}
    if "Colors:" in raw:
        color_part = raw.split("Colors:", 1)[1]
        for pair in color_part.split(","):
            if "=" in pair:
                k, v = pair.split("=", 1)
                colors[k.strip()] = v.strip()
    return {"chart_type": chart_type, "colors": colors or None, "status_for_display": status.value}


def _document_set_version(source_availability: Dict[str, str]) -> str:
    """Real (not placeholder) document-set identity: a hash of exactly
    which source types were available/searched and what happened for each.
    Changes automatically the moment the underlying document set changes
    (a new upload makes a previously-SOURCE_UNAVAILABLE type become
    SEARCHED_*), so a stale result is naturally distinguishable without a
    DB schema change."""
    key = "|".join(f"{k}={v}" for k, v in sorted(source_availability.items()))
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:16]


def _source_available(source_type: str, symbol: str) -> bool:
    """Real (not simulated) availability check.

    In the manual document-upload workflow (`tools.manual_mode.
    is_manual_mode()`), live-scraper-backed sources (governance/
    shareholding/insider/CRISIL) are NOT attempted - this mirrors the
    EXISTING legacy compute_fn guard (the same ContextVar-based
    `manual_mode()` check documented in `document_analysis_engine.
    run_qualitative_analysis`'s `_run_one` - "wrapping the ex.map() call
    ... left is_manual_mode() False inside every worker, silently letting
    every compute_fn's live-fetch guard ... fall through to a real
    external call despite this being the document-only manual workflow").
    Per spec section 18: "Do not silently substitute live web financial
    data" for the manual-upload workflow - only the Annual Report (the
    document actually being analysed) and genuinely uploaded supporting
    documents are available sources in that mode.

    Outside manual mode (the automatic live pipeline), the 4 live-scraper
    sources + Annual Report are always attempted; every upload-only type
    uses the EXISTING `_manual_doc_uploaded` check (never duplicated)."""
    try:
        from tools.manual_mode import is_manual_mode
        manual = is_manual_mode()
    except Exception:
        manual = False

    if source_type in _ALWAYS_ATTEMPTED_SOURCES:
        if source_type == "annual_report":
            return True
        return not manual  # live scrapers only outside manual mode

    try:
        from tools.qualitative_engine import _manual_doc_uploaded
        result = _manual_doc_uploaded(symbol, source_type)
        return bool(result)
    except Exception:
        return False


def _extract_for_concept(concept: str, symbol: str, name: Optional[str], fiscal_year: Optional[int],
                          task_key: str, subtask_key: str) -> EvidenceBundle:
    """Dispatches one required-evidence concept to its extraction
    primitive - structured primitive if one exists for this concept,
    otherwise the generic text-based primitive. Availability is checked
    PER SOURCE TYPE the primitive would actually use, so a missing source
    never gets silently reported as NOT_DISCLOSED (spec requirement #8)."""
    if concept in STRUCTURED_PRIMITIVES:
        fn = _STRUCTURED_EXTRACTORS.get(STRUCTURED_PRIMITIVES[concept])
        source_type = _CONCEPT_SOURCE_TYPE.get(STRUCTURED_PRIMITIVES[concept], "annual_report")
        if not _source_available(source_type, symbol):
            bundle = EvidenceBundle(company_identity=symbol, fiscal_year=fiscal_year,
                                     task_key=task_key, subtask_key=subtask_key)
            bundle.source_availability[source_type] = resolve_availability(available=False, searched=False)
            return bundle
        return fn(symbol, name, fiscal_year, task_key, subtask_key)

    if concept in TEXT_BASED_CONCEPTS:
        if not _source_available("annual_report", symbol):
            bundle = EvidenceBundle(company_identity=symbol, fiscal_year=fiscal_year,
                                     task_key=task_key, subtask_key=subtask_key)
            bundle.source_availability["annual_report"] = resolve_availability(available=False, searched=False)
            return bundle
        return extract_text_based_evidence(symbol, name, fiscal_year, task_key, subtask_key,
                                            concept, cache_prefix=f"qte_{concept}_v1")

    bundle = EvidenceBundle(company_identity=symbol, fiscal_year=fiscal_year,
                             task_key=task_key, subtask_key=subtask_key)
    return bundle


def _merge_bundles(primary: EvidenceBundle, other: EvidenceBundle) -> None:
    primary.evidence.extend(other.evidence)
    primary.source_availability.update(other.source_availability)


def _interpret(status: EvidenceStatus, bundle: EvidenceBundle) -> str:
    """Generic, task-agnostic interpretation string - a human-readable
    summary of what the evidence bundle actually contains. Never invents
    a business conclusion the evidence doesn't support (spec's "never
    infer intent" rule) - just describes what was found/not found/where."""
    if status == EvidenceStatus.NOT_APPLICABLE:
        return "This item is not applicable to this company (sector/structure gate)."
    if status == EvidenceStatus.INSUFFICIENT_EVIDENCE:
        searched = [k for k, v in bundle.source_availability.items()
                    if v.value not in ("SEARCHED_FOUND", "SEARCHED_NOT_FOUND")]
        return f"Could not be evaluated - required source(s) unavailable or unsearchable: {searched}."
    if status == EvidenceStatus.NOT_DISCLOSED:
        searched = [k for k, v in bundle.source_availability.items()
                    if v.value in ("SEARCHED_FOUND", "SEARCHED_NOT_FOUND")]
        return f"Not disclosed - searched {searched or ['available sources']}, no evidence found."
    if status == EvidenceStatus.VERIFIED_ABSENT:
        ex = bundle.evidence[0].extracted_text if bundle.evidence else None
        return f"The filing explicitly states this does not apply/exist: \"{ex}\"" if ex else \
            "The filing explicitly states this does not apply/exist."
    if status == EvidenceStatus.CONTRADICTORY_EVIDENCE:
        pairs = bundle.contradicting_pairs()
        if pairs:
            a, b = pairs[0]
            return (f"Sources disagree: {a.source_document_type} reports {a.normalized_value!r}, "
                    f"{b.source_document_type} reports {b.normalized_value!r}.")
        return "Evidence from different sources disagrees; not resolved automatically."
    if status == EvidenceStatus.VERIFIED:
        return f"Corroborated across {len({e.source_document_type for e in bundle.evidence})} independent sources."
    if status == EvidenceStatus.PARTIALLY_VERIFIED:
        ex = bundle.evidence[0].extracted_text if bundle.evidence else None
        return f"Single-source evidence found: \"{ex}\"" if ex else "Single-source evidence found."
    return "Could not be evaluated."


def _score_for(status: EvidenceStatus, bundle: EvidenceBundle):
    """Per instruction #12: score is populated ONLY when the evidence
    IS the score (a directly-disclosed structured value, e.g. promoter
    ownership %/pledge %) - never a manufactured rubric score. Every
    other concept (narrative text evidence with no parseable numeric
    rubric wired yet) returns score=None, score_scale=None - honest
    absence, not a fabricated number."""
    numeric_concepts = {"promoter_ownership", "promoter_pledge", "institutional_ownership"}
    for ev in bundle.evidence:
        if ev.evidence_type in numeric_concepts and isinstance(ev.normalized_value, (int, float)):
            return ev.normalized_value, "percent"
    # Categorical concepts whose classification IS the analytical result
    # (e.g. segment_concentration_threshold's Single Product / Portfolio
    # classification, per the task's own real formula_or_matrix rule -
    # spec section 5) - still not a manufactured numeric rubric score.
    categorical_concepts = {"segment_concentration_threshold"}
    for ev in bundle.evidence:
        if ev.evidence_type in categorical_concepts and isinstance(ev.normalized_value, str):
            return ev.normalized_value, "categorical"

    # Auditor opinion - the registry's OWN 1-5 severity rule (C.6.3's
    # formula_or_matrix: "unmodified = highest; qualifications reduce score
    # according to severity"), via the shared qualitative_scoring_primitives
    # module (spec section 4 - consolidated scoring mechanics, not a
    # per-task reimplementation). Falls back to the plain categorical label
    # (spec section 5 example task, no numeric scale) when no numeric
    # mapping applies.
    for ev in bundle.evidence:
        if ev.evidence_type == "auditor_qualification" and ev.extracted_text:
            from tools.qualitative_scoring_primitives import interpret_audit_opinion_severity_score
            score = interpret_audit_opinion_severity_score(ev.extracted_text)
            if score is not None:
                return score, "score(1-5)"
    return None, None


def evaluate_task(symbol: str, name: Optional[str], fiscal_year: Optional[int], task_id: str,
                   force: bool = False) -> QualitativeResult:
    """The single universal entry point (spec section 1). Never raises.
    Returns a QualitativeResult for ANY registry task_id, including ones
    whose evidence contract is still incomplete (status NEEDS_REVIEW,
    never a fabricated result) - see `_evidence_contract_complete`."""
    sym = (symbol or "").strip().upper().replace(".NS", "")
    task = TASK_BY_ID.get(task_id)
    if task is None:
        return QualitativeResult(
            company_identity=sym, fiscal_year=fiscal_year, task_key=task_id, subtask_key=task_id,
            score=None, score_scale=None, status=EvidenceStatus.ERROR,
            confidence=Confidence(ConfidenceTier.UNKNOWN, None, "unknown task_id"),
            interpretation=f"Unknown task_id '{task_id}'.",
        )

    task_key = task.get("parent_id") or task_id

    if not force:
        cached = read_qualitative(sym, task_id)
        if cached and cached.get("_engine") == _ENGINE_MARKER \
                and cached.get("_extraction_version") == QUALITATIVE_EXTRACTION_VERSION \
                and cached.get("_engine_version") == QUALITATIVE_ENGINE_VERSION:
            return QualitativeResult(
                company_identity=sym, fiscal_year=fiscal_year, task_key=cached.get("task_key", task_key),
                subtask_key=task_id, score=cached.get("score"), score_scale=cached.get("score_scale"),
                status=EvidenceStatus(cached.get("status", "ERROR")),
                confidence=Confidence(ConfidenceTier(cached.get("confidence_tier", "UNKNOWN")),
                                       cached.get("confidence_score"), cached.get("confidence_reason", "")),
                interpretation=cached.get("rationale", ""), evidence=[], provenance=cached.get("provenance") or [],
                visualization_metadata=cached.get("visualization_metadata"),
                document_set_version=cached.get("_document_set_version"), from_cache=True,
            )

    from tools.qualitative_legacy_adapters import (
        LEGACY_AR_TEXT_SCORER_ADAPTERS, evaluate_via_legacy_scorer,
        LEGACY_TABLE_TEXT_ADAPTERS, evaluate_via_legacy_table_scorer,
        LEGACY_PRIVATE_HELPER_ADAPTERS, evaluate_via_private_helper_scorer,
        LEGACY_RPT_EVIDENCE_ADAPTERS, evaluate_via_rpt_evidence_scorer,
        LEGACY_GOVERNANCE_FILING_ADAPTERS, evaluate_via_governance_filing_scorer,
    )
    _adapter_tables = (
        (LEGACY_AR_TEXT_SCORER_ADAPTERS, evaluate_via_legacy_scorer),
        (LEGACY_TABLE_TEXT_ADAPTERS, evaluate_via_legacy_table_scorer),
        (LEGACY_PRIVATE_HELPER_ADAPTERS, evaluate_via_private_helper_scorer),
        (LEGACY_RPT_EVIDENCE_ADAPTERS, evaluate_via_rpt_evidence_scorer),
        (LEGACY_GOVERNANCE_FILING_ADAPTERS, evaluate_via_governance_filing_scorer),
    )
    _matched_adapter_fn = next((fn for table, fn in _adapter_tables if task_id in table), None)
    if _matched_adapter_fn is not None and not task.get("llm_dependent") and not task.get("derived_rollup"):
        bundle = _matched_adapter_fn(sym, name, fiscal_year, task_key, task_id)
        status, confidence = bundle.classify()
        interpretation = _interpret(status, bundle)
        score = getattr(bundle, "legacy_score", None)
        score_scale = "score(1-5)" if isinstance(score, (int, float)) and 1 <= score <= 5 else \
            ("score" if score is not None else None)
        provenance = [{
            "source_document": e.source_document, "source_document_type": e.source_document_type,
            "page_number": e.page_number, "section": e.section, "heading": e.heading,
            "extracted_text": e.extracted_text, "extraction_method": e.extraction_method,
            "evidence_date": e.evidence_date, "evidence_id": e.evidence_id,
        } for e in bundle.evidence]
        doc_set_version = _document_set_version({k: v.value for k, v in bundle.source_availability.items()})
        result = QualitativeResult(
            company_identity=sym, fiscal_year=fiscal_year, task_key=task_key, subtask_key=task_id,
            score=score, score_scale=score_scale, status=status, confidence=confidence,
            interpretation=interpretation, evidence=bundle.evidence, provenance=provenance,
            visualization_metadata=_visualization_metadata(task, status), document_set_version=doc_set_version,
        )
        write_qualitative(sym, task_id, result.to_payload(), status.value, name=name)
        return result

    required = task.get("required_evidence_types") or []
    if not required:
        # Honest per spec section 13 - K-U (and any other) tasks whose
        # evidence contract is not yet populated are NOT silently skipped
        # or fabricated; they report exactly why.
        result = QualitativeResult(
            company_identity=sym, fiscal_year=fiscal_year, task_key=task_key, subtask_key=task_id,
            score=None, score_scale=None, status=EvidenceStatus.NEEDS_REVIEW,
            confidence=Confidence(ConfidenceTier.UNKNOWN, None, "evidence contract not yet defined"),
            interpretation="This task's evidence contract is not yet complete in the registry "
                           "(no required_evidence_types wired) - not evaluated by the universal engine yet.",
            visualization_metadata=_visualization_metadata(task, EvidenceStatus.NEEDS_REVIEW),
            document_set_version=None,
        )
        write_qualitative(sym, task_id, result.to_payload(), result.status.value, name=name)
        return result

    if task.get("llm_dependent") or task.get("derived_rollup"):
        result = QualitativeResult(
            company_identity=sym, fiscal_year=fiscal_year, task_key=task_key, subtask_key=task_id,
            score=None, score_scale=None, status=EvidenceStatus.NEEDS_REVIEW,
            confidence=Confidence(ConfidenceTier.UNKNOWN, None, "llm_dependent or derived_rollup task"),
            interpretation="This task is LLM-dependent or a derived rollup - not handled by the "
                           "universal evidence engine yet (legacy compute_fn only).",
            visualization_metadata=_visualization_metadata(task, EvidenceStatus.NEEDS_REVIEW),
        )
        return result

    bundle = EvidenceBundle(company_identity=sym, fiscal_year=fiscal_year, task_key=task_key, subtask_key=task_id)
    for concept in required:
        sub_bundle = _extract_for_concept(concept, sym, name, fiscal_year, task_key, task_id)
        _merge_bundles(bundle, sub_bundle)

    status, confidence = bundle.classify()
    interpretation = _interpret(status, bundle)
    score, score_scale = _score_for(status, bundle)
    provenance = [{
        "source_document": e.source_document, "source_document_type": e.source_document_type,
        "page_number": e.page_number, "section": e.section, "heading": e.heading,
        "extracted_text": e.extracted_text, "extraction_method": e.extraction_method,
        "evidence_date": e.evidence_date, "evidence_id": e.evidence_id,
    } for e in bundle.evidence]
    doc_set_version = _document_set_version({k: v.value for k, v in bundle.source_availability.items()})

    result = QualitativeResult(
        company_identity=sym, fiscal_year=fiscal_year, task_key=task_key, subtask_key=task_id,
        score=score, score_scale=score_scale, status=status, confidence=confidence,
        interpretation=interpretation, evidence=bundle.evidence, provenance=provenance,
        visualization_metadata=_visualization_metadata(task, status), document_set_version=doc_set_version,
    )
    write_qualitative(sym, task_id, result.to_payload(), status.value, name=name)
    return result
