// NSE Sector Map — official industry classification for the Nifty Total
// Market index constituents (751 companies), sourced from NSE's own
// published "ind_niftytotalmarket_list.csv" (Industry column), mapped 1:1
// onto the 26-sector taxonomy in sectorMatrix.js. Two NSE macro categories
// ("Financial Services", "Healthcare") don't distinguish Banks/NBFC/
// Insurance/Capital Markets or Pharmaceuticals/Healthcare Services the way
// this app's matrix requires, so those rows were sub-classified by a
// deterministic company-name keyword test (bank/insurance/exchange/AMC/
// broking/wealth keywords for Financial Services; hospital/diagnostic/
// clinic keywords for Healthcare) — NOT a fuzzy/AI guess, just an explicit
// alias list, same approach as normalizeSectorLabel's own fallback.
//
// COVERAGE CAVEAT: this is the Nifty TOTAL MARKET list — the ~750 most
// liquid/tracked NSE equities, not the full ~2,400+ symbol universe this
// app's registry covers. NSE does not publish a free, public industry
// classification file for the full universe anywhere found so far —
// smaller/micro-cap symbols not in this map fall through to the looser
// normalizeSectorLabel() heuristic (or show "sector could not be
// resolved" if that also comes up empty). Precomputed once, shipped as a
// static lookup — same "exactly two O(1) lookups" performance rule as
// the rest of the sector-tiering system.
export const NSE_SECTOR_BY_SYMBOL = {
  "360ONE": "Capital Markets (Broking/AMC/Exchanges)",
  "3MINDIA": "Diversified",
  "AADHARHFC": "NBFC",
  "AARTIDRUGS": "Pharmaceuticals",
  "AARTIIND": "Chemicals",
  "AARTIPHARM": "Pharmaceuticals",
  "AAVAS": "NBFC",
  "ABB": "Capital Goods",
  "ABBOTINDIA": "Pharmaceuticals",
  "ABCAPITAL": "NBFC",
  "ABDL": "Fast Moving Consumer Goods (FMCG)",
  "ABFRL": "Consumer Services",
  "ABLBL": "Consumer Services",
  "ABREL": "Realty",
  "ABSLAMC": "Capital Markets (Broking/AMC/Exchanges)",
  "ACC": "Construction Materials (Cement)",
  "ACE": "Capital Goods",
  "ACI": "Chemicals",
  "ACMESOLAR": "Power",
  "ACUTAAS": "Pharmaceuticals",
  "ADANIENSOL": "Power",
  "ADANIENT": "Metals & Mining",
  "ADANIGREEN": "Power",
  "ADANIPORTS": "Services (Logistics/Transportation/Aviation)",
  "ADANIPOWER": "Power",
  "ADVENZYMES": "Pharmaceuticals",
  "AEGISLOG": "Oil, Gas & Consumable Fuels",
  "AEGISVOPAK": "Oil, Gas & Consumable Fuels",
  "AEQUS": "Capital Goods",
  "AETHER": "Chemicals",
  "AFCONS": "Construction",
  "AFFLE": "Information Technology",
  "AGARWALEYE": "Healthcare Services (Hospitals/Diagnostics)",
  "AGL": "Services (Logistics/Transportation/Aviation)",
  "AHLUCONT": "Construction",
  "AIAENG": "Capital Goods",
  "AIIL": "NBFC",
  "AJANTPHARM": "Pharmaceuticals",
  "AKUMS": "Pharmaceuticals",
  "ALIVUS": "Pharmaceuticals",
  "ALKEM": "Pharmaceuticals",
  "ALKYLAMINE": "Chemicals",
  "ALOKINDS": "Textiles",
  "AMBER": "Consumer Durables",
  "AMBUJACEM": "Construction Materials (Cement)",
  "ANANDRATHI": "Capital Markets (Broking/AMC/Exchanges)",
  "ANANTRAJ": "Realty",
  "ANGELONE": "NBFC",
  "ANTHEM": "Pharmaceuticals",
  "ANUP": "Capital Goods",
  "ANURAS": "Chemicals",
  "APARINDS": "Capital Goods",
  "APLAPOLLO": "Capital Goods",
  "APLLTD": "Pharmaceuticals",
  "APOLLO": "Capital Goods",
  "APOLLOHOSP": "Healthcare Services (Hospitals/Diagnostics)",
  "APOLLOTYRE": "Automobile & Auto Components",
  "APTUS": "NBFC",
  "ARE&M": "Automobile & Auto Components",
  "ARVIND": "Textiles",
  "ARVINDFASN": "Consumer Services",
  "ASAHIINDIA": "Automobile & Auto Components",
  "ASHAPURMIN": "Metals & Mining",
  "ASHOKA": "Construction",
  "ASHOKLEY": "Capital Goods",
  "ASIANPAINT": "Consumer Durables",
  "ASKAUTOLTD": "Automobile & Auto Components",
  "ASTERDM": "Healthcare Services (Hospitals/Diagnostics)",
  "ASTRAL": "Capital Goods",
  "ASTRAMICRO": "Capital Goods",
  "ATGL": "Oil, Gas & Consumable Fuels",
  "ATHERENERG": "Automobile & Auto Components",
  "ATLANTAELE": "Capital Goods",
  "ATUL": "Chemicals",
  "AUBANK": "Banks",
  "AURIONPRO": "Information Technology",
  "AUROPHARMA": "Pharmaceuticals",
  "AVALON": "Capital Goods",
  "AVANTIFEED": "Fast Moving Consumer Goods (FMCG)",
  "AVL": "Consumer Services",
  "AWFIS": "Services (Logistics/Transportation/Aviation)",
  "AWL": "Fast Moving Consumer Goods (FMCG)",
  "AXISBANK": "Banks",
  "AXISCADES": "Capital Goods",
  "AZAD": "Capital Goods",
  "BAJAJ-AUTO": "Automobile & Auto Components",
  "BAJAJELEC": "Consumer Durables",
  "BAJAJFINSV": "NBFC",
  "BAJAJHFL": "NBFC",
  "BAJAJHLDNG": "NBFC",
  "BAJFINANCE": "NBFC",
  "BALAMINES": "Chemicals",
  "BALKRISIND": "Automobile & Auto Components",
  "BALRAMCHIN": "Fast Moving Consumer Goods (FMCG)",
  "BALUFORGE": "Capital Goods",
  "BANCOINDIA": "Automobile & Auto Components",
  "BANDHANBNK": "Banks",
  "BANKBARODA": "Banks",
  "BANKINDIA": "Banks",
  "BATAINDIA": "Consumer Durables",
  "BAYERCROP": "Chemicals",
  "BBOX": "Information Technology",
  "BBTC": "Fast Moving Consumer Goods (FMCG)",
  "BDL": "Capital Goods",
  "BECTORFOOD": "Fast Moving Consumer Goods (FMCG)",
  "BEL": "Capital Goods",
  "BELRISE": "Automobile & Auto Components",
  "BEML": "Capital Goods",
  "BERGEPAINT": "Consumer Durables",
  "BHARATFORG": "Automobile & Auto Components",
  "BHARTIARTL": "Telecommunication",
  "BHARTIHEXA": "Telecommunication",
  "BHEL": "Capital Goods",
  "BIKAJI": "Fast Moving Consumer Goods (FMCG)",
  "BIOCON": "Pharmaceuticals",
  "BIRLACORPN": "Construction Materials (Cement)",
  "BLACKBUCK": "Services (Logistics/Transportation/Aviation)",
  "BLS": "Consumer Services",
  "BLUEDART": "Services (Logistics/Transportation/Aviation)",
  "BLUEJET": "Healthcare Services (Hospitals/Diagnostics)",
  "BLUESTARCO": "Consumer Durables",
  "BLUESTONE": "Consumer Durables",
  "BORORENEW": "Capital Goods",
  "BOSCHLTD": "Automobile & Auto Components",
  "BPCL": "Oil, Gas & Consumable Fuels",
  "BRIGADE": "Realty",
  "BRITANNIA": "Fast Moving Consumer Goods (FMCG)",
  "BSE": "NBFC",
  "BSOFT": "Information Technology",
  "CAMPUS": "Consumer Durables",
  "CAMS": "NBFC",
  "CANBK": "Banks",
  "CANFINHOME": "NBFC",
  "CANHLIFE": "Insurance",
  "CAPILLARY": "Information Technology",
  "CAPLIPOINT": "Pharmaceuticals",
  "CARBORUNIV": "Capital Goods",
  "CARTRADE": "Consumer Services",
  "CASTROLIND": "Oil, Gas & Consumable Fuels",
  "CCAVENUE": "NBFC",
  "CCL": "Fast Moving Consumer Goods (FMCG)",
  "CDSL": "Capital Markets (Broking/AMC/Exchanges)",
  "CEATLTD": "Automobile & Auto Components",
  "CELLO": "Consumer Durables",
  "CEMPRO": "Construction",
  "CENTRALBK": "Banks",
  "CENTURYPLY": "Consumer Durables",
  "CERA": "Consumer Durables",
  "CESC": "Power",
  "CGCL": "NBFC",
  "CGPOWER": "Capital Goods",
  "CHALET": "Consumer Services",
  "CHAMBLFERT": "Chemicals",
  "CHENNPETRO": "Oil, Gas & Consumable Fuels",
  "CHOICEIN": "NBFC",
  "CHOLAFIN": "NBFC",
  "CHOLAHLDNG": "NBFC",
  "CIEINDIA": "Automobile & Auto Components",
  "CIPLA": "Pharmaceuticals",
  "CLEAN": "Chemicals",
  "CMSINFO": "Services (Logistics/Transportation/Aviation)",
  "COALINDIA": "Oil, Gas & Consumable Fuels",
  "COCHINSHIP": "Capital Goods",
  "COFORGE": "Information Technology",
  "COHANCE": "Pharmaceuticals",
  "COLPAL": "Fast Moving Consumer Goods (FMCG)",
  "CONCOR": "Services (Logistics/Transportation/Aviation)",
  "CONCORDBIO": "Pharmaceuticals",
  "COROMANDEL": "Chemicals",
  "CORONA": "Pharmaceuticals",
  "CPPLUS": "Capital Goods",
  "CRAFTSMAN": "Automobile & Auto Components",
  "CRAMC": "Capital Markets (Broking/AMC/Exchanges)",
  "CREDITACC": "NBFC",
  "CRISIL": "NBFC",
  "CRIZAC": "Consumer Services",
  "CROMPTON": "Consumer Durables",
  "CSBBANK": "Banks",
  "CUB": "Banks",
  "CUMMINSIND": "Capital Goods",
  "CUPID": "Fast Moving Consumer Goods (FMCG)",
  "CYIENT": "Information Technology",
  "DABUR": "Fast Moving Consumer Goods (FMCG)",
  "DALBHARAT": "Construction Materials (Cement)",
  "DATAMATICS": "Information Technology",
  "DATAPATTNS": "Capital Goods",
  "DBL": "Construction",
  "DBREALTY": "Realty",
  "DCBBANK": "Banks",
  "DCMSHRIRAM": "Diversified",
  "DEEPAKFERT": "Chemicals",
  "DEEPAKNTR": "Chemicals",
  "DELHIVERY": "Services (Logistics/Transportation/Aviation)",
  "DEVYANI": "Consumer Services",
  "DIACABS": "Capital Goods",
  "DIVISLAB": "Pharmaceuticals",
  "DIXON": "Consumer Durables",
  "DLF": "Realty",
  "DMART": "Consumer Services",
  "DOMS": "Fast Moving Consumer Goods (FMCG)",
  "DRREDDY": "Pharmaceuticals",
  "DYNAMATECH": "Capital Goods",
  "ECLERX": "Services (Logistics/Transportation/Aviation)",
  "EDELWEISS": "NBFC",
  "EICHERMOT": "Automobile & Auto Components",
  "EIDPARRY": "Fast Moving Consumer Goods (FMCG)",
  "EIEL": "Capital Goods",
  "EIHOTEL": "Consumer Services",
  "ELECON": "Capital Goods",
  "ELECTCAST": "Capital Goods",
  "ELGIEQUIP": "Capital Goods",
  "ELLEN": "Chemicals",
  "EMAMILTD": "Fast Moving Consumer Goods (FMCG)",
  "EMBDL": "Realty",
  "EMCURE": "Pharmaceuticals",
  "EMIL": "Consumer Services",
  "EMMVEE": "Capital Goods",
  "ENDURANCE": "Automobile & Auto Components",
  "ENGINERSIN": "Construction",
  "ENRIN": "Capital Goods",
  "ENTERO": "Consumer Services",
  "EPL": "Capital Goods",
  "EQUITASBNK": "Banks",
  "ERIS": "Pharmaceuticals",
  "ESCORTS": "Capital Goods",
  "ETERNAL": "Consumer Services",
  "ETHOSLTD": "Consumer Durables",
  "EUREKAFORB": "Consumer Durables",
  "EXIDEIND": "Automobile & Auto Components",
  "FACT": "Chemicals",
  "FEDERALBNK": "Banks",
  "FEDFINA": "Banks",
  "FIEMIND": "Automobile & Auto Components",
  "FINCABLES": "Capital Goods",
  "FINPIPE": "Capital Goods",
  "FIRSTCRY": "Consumer Services",
  "FIVESTAR": "NBFC",
  "FLUOROCHEM": "Chemicals",
  "FORCEMOT": "Automobile & Auto Components",
  "FORTIS": "Healthcare Services (Hospitals/Diagnostics)",
  "FSL": "Services (Logistics/Transportation/Aviation)",
  "GABRIEL": "Automobile & Auto Components",
  "GAEL": "Fast Moving Consumer Goods (FMCG)",
  "GAIL": "Oil, Gas & Consumable Fuels",
  "GALLANTT": "Capital Goods",
  "GESHIP": "Services (Logistics/Transportation/Aviation)",
  "GHCL": "Chemicals",
  "GICRE": "Insurance",
  "GILLETTE": "Fast Moving Consumer Goods (FMCG)",
  "GLAND": "Pharmaceuticals",
  "GLAXO": "Pharmaceuticals",
  "GLENMARK": "Pharmaceuticals",
  "GMDCLTD": "Metals & Mining",
  "GMMPFAUDLR": "Capital Goods",
  "GMRAIRPORT": "Services (Logistics/Transportation/Aviation)",
  "GMRP&UI": "Power",
  "GNFC": "Chemicals",
  "GODFRYPHLP": "Fast Moving Consumer Goods (FMCG)",
  "GODIGIT": "Insurance",
  "GODREJAGRO": "Fast Moving Consumer Goods (FMCG)",
  "GODREJCP": "Fast Moving Consumer Goods (FMCG)",
  "GODREJIND": "Diversified",
  "GODREJPROP": "Realty",
  "GOKEX": "Textiles",
  "GOKULAGRO": "Fast Moving Consumer Goods (FMCG)",
  "GPIL": "Capital Goods",
  "GPPL": "Services (Logistics/Transportation/Aviation)",
  "GRANULES": "Pharmaceuticals",
  "GRAPHITE": "Capital Goods",
  "GRASIM": "Construction Materials (Cement)",
  "GRAVITA": "Metals & Mining",
  "GREAVESCOT": "Capital Goods",
  "GRINDWELL": "Capital Goods",
  "GROWW": "NBFC",
  "GRSE": "Capital Goods",
  "GRWRHITECH": "Capital Goods",
  "GSFC": "Chemicals",
  "GVT&D": "Capital Goods",
  "HAL": "Capital Goods",
  "HAPPSTMNDS": "Information Technology",
  "HAVELLS": "Consumer Durables",
  "HBLENGINE": "Capital Goods",
  "HCC": "Construction",
  "HCG": "Healthcare Services (Hospitals/Diagnostics)",
  "HCLTECH": "Information Technology",
  "HDBFS": "NBFC",
  "HDFCAMC": "Capital Markets (Broking/AMC/Exchanges)",
  "HDFCBANK": "Banks",
  "HDFCLIFE": "Insurance",
  "HEG": "Capital Goods",
  "HEMIPROP": "Services (Logistics/Transportation/Aviation)",
  "HERITGFOOD": "Fast Moving Consumer Goods (FMCG)",
  "HEROMOTOCO": "Automobile & Auto Components",
  "HEXT": "Information Technology",
  "HFCL": "Telecommunication",
  "HGINFRA": "Construction",
  "HINDALCO": "Metals & Mining",
  "HINDCOPPER": "Metals & Mining",
  "HINDPETRO": "Oil, Gas & Consumable Fuels",
  "HINDUNILVR": "Fast Moving Consumer Goods (FMCG)",
  "HINDZINC": "Metals & Mining",
  "HOMEFIRST": "NBFC",
  "HONASA": "Fast Moving Consumer Goods (FMCG)",
  "HONAUT": "Capital Goods",
  "HSCL": "Chemicals",
  "HUDCO": "NBFC",
  "HYUNDAI": "Automobile & Auto Components",
  "ICICIAMC": "Capital Markets (Broking/AMC/Exchanges)",
  "ICICIBANK": "Banks",
  "ICICIGI": "Insurance",
  "ICICIPRULI": "Insurance",
  "ICIL": "Textiles",
  "IDBI": "Banks",
  "IDEA": "Telecommunication",
  "IDFCFIRSTB": "Banks",
  "IEX": "Capital Markets (Broking/AMC/Exchanges)",
  "IFBIND": "Consumer Durables",
  "IFCI": "NBFC",
  "IGIL": "Services (Logistics/Transportation/Aviation)",
  "IGL": "Oil, Gas & Consumable Fuels",
  "IIFL": "NBFC",
  "IIFLCAPS": "NBFC",
  "IKS": "Information Technology",
  "IMFA": "Metals & Mining",
  "INDGN": "Pharmaceuticals",
  "INDHOTEL": "Consumer Services",
  "INDIACEM": "Construction Materials (Cement)",
  "INDIAGLYCO": "Fast Moving Consumer Goods (FMCG)",
  "INDIAMART": "Consumer Services",
  "INDIANB": "Banks",
  "INDIASHLTR": "NBFC",
  "INDIGO": "Services (Logistics/Transportation/Aviation)",
  "INDIGOPNTS": "Consumer Durables",
  "INDUSINDBK": "Banks",
  "INDUSTOWER": "Telecommunication",
  "INFY": "Information Technology",
  "INOXGREEN": "Services (Logistics/Transportation/Aviation)",
  "INOXINDIA": "Capital Goods",
  "INOXWIND": "Capital Goods",
  "INTELLECT": "Information Technology",
  "IOB": "Banks",
  "IOC": "Oil, Gas & Consumable Fuels",
  "IONEXCHANG": "Capital Goods",
  "IPCALAB": "Pharmaceuticals",
  "IRB": "Construction",
  "IRCON": "Construction",
  "IRCTC": "Consumer Services",
  "IREDA": "NBFC",
  "IRFC": "NBFC",
  "ITC": "Fast Moving Consumer Goods (FMCG)",
  "ITCHOTELS": "Consumer Services",
  "ITI": "Telecommunication",
  "IXIGO": "Consumer Services",
  "J&KBANK": "Banks",
  "JAIBALAJI": "Metals & Mining",
  "JAINREC": "Metals & Mining",
  "JAMNAAUTO": "Automobile & Auto Components",
  "JAYNECOIND": "Capital Goods",
  "JBMA": "Automobile & Auto Components",
  "JINDALSAW": "Capital Goods",
  "JINDALSTEL": "Metals & Mining",
  "JIOFIN": "NBFC",
  "JKCEMENT": "Construction Materials (Cement)",
  "JKLAKSHMI": "Construction Materials (Cement)",
  "JKPAPER": "Forest Materials (Paper)",
  "JKTYRE": "Automobile & Auto Components",
  "JLHL": "Healthcare Services (Hospitals/Diagnostics)",
  "JMFINANCIL": "NBFC",
  "JPPOWER": "Power",
  "JSFB": "Banks",
  "JSL": "Metals & Mining",
  "JSLL": "Consumer Services",
  "JSWCEMENT": "Construction Materials (Cement)",
  "JSWDULUX": "Consumer Durables",
  "JSWENERGY": "Power",
  "JSWINFRA": "Services (Logistics/Transportation/Aviation)",
  "JSWSTEEL": "Metals & Mining",
  "JUBLFOOD": "Consumer Services",
  "JUBLINGREA": "Chemicals",
  "JUBLPHARMA": "Pharmaceuticals",
  "JUSTDIAL": "Consumer Services",
  "JWL": "Capital Goods",
  "JYOTHYLAB": "Fast Moving Consumer Goods (FMCG)",
  "JYOTICNC": "Capital Goods",
  "KAJARIACER": "Consumer Durables",
  "KALYANKJIL": "Consumer Durables",
  "KANSAINER": "Consumer Durables",
  "KARURVYSYA": "Banks",
  "KAYNES": "Capital Goods",
  "KEC": "Construction",
  "KEI": "Capital Goods",
  "KFINTECH": "NBFC",
  "KIMS": "Pharmaceuticals",
  "KIRLOSBROS": "Capital Goods",
  "KIRLOSENG": "Capital Goods",
  "KIRLPNU": "Capital Goods",
  "KITEX": "Textiles",
  "KNRCON": "Construction",
  "KOTAKBANK": "Banks",
  "KPIGREEN": "Power",
  "KPIL": "Construction",
  "KPITTECH": "Information Technology",
  "KPRMILL": "Textiles",
  "KRBL": "Fast Moving Consumer Goods (FMCG)",
  "KRN": "Capital Goods",
  "KSB": "Capital Goods",
  "KSCL": "Fast Moving Consumer Goods (FMCG)",
  "KTKBANK": "Banks",
  "LALPATHLAB": "Pharmaceuticals",
  "LATENTVIEW": "Information Technology",
  "LAURUSLABS": "Pharmaceuticals",
  "LEMONTREE": "Consumer Services",
  "LENSKART": "Consumer Services",
  "LGEINDIA": "Consumer Durables",
  "LICHSGFIN": "NBFC",
  "LICI": "Insurance",
  "LINDEINDIA": "Chemicals",
  "LLOYDSENGG": "Capital Goods",
  "LLOYDSENT": "Metals & Mining",
  "LLOYDSME": "Metals & Mining",
  "LODHA": "Realty",
  "LOTUSDEV": "Realty",
  "LT": "Construction",
  "LTF": "NBFC",
  "LTFOODS": "Fast Moving Consumer Goods (FMCG)",
  "LTM": "Information Technology",
  "LTTS": "Information Technology",
  "LUMAXTECH": "Automobile & Auto Components",
  "LUPIN": "Pharmaceuticals",
  "LXCHEM": "Chemicals",
  "M&M": "Automobile & Auto Components",
  "M&MFIN": "NBFC",
  "MAHABANK": "Banks",
  "MAHSCOOTER": "NBFC",
  "MAHSEAMLES": "Capital Goods",
  "MANAPPURAM": "NBFC",
  "MANKIND": "Pharmaceuticals",
  "MANORAMA": "Fast Moving Consumer Goods (FMCG)",
  "MANYAVAR": "Consumer Services",
  "MAPMYINDIA": "Information Technology",
  "MARICO": "Fast Moving Consumer Goods (FMCG)",
  "MARKSANS": "Pharmaceuticals",
  "MARUTI": "Automobile & Auto Components",
  "MASTEK": "Information Technology",
  "MAXHEALTH": "Healthcare Services (Hospitals/Diagnostics)",
  "MAZDOCK": "Capital Goods",
  "MCX": "Capital Markets (Broking/AMC/Exchanges)",
  "MEDANTA": "Healthcare Services (Hospitals/Diagnostics)",
  "MEDPLUS": "Consumer Services",
  "MEESHO": "Consumer Services",
  "METROPOLIS": "Healthcare Services (Hospitals/Diagnostics)",
  "MFSL": "NBFC",
  "MGL": "Oil, Gas & Consumable Fuels",
  "MIDHANI": "Capital Goods",
  "MINDACORP": "Automobile & Auto Components",
  "MMTC": "Services (Logistics/Transportation/Aviation)",
  "MOIL": "Metals & Mining",
  "MOTHERSON": "Automobile & Auto Components",
  "MOTILALOFS": "NBFC",
  "MPHASIS": "Information Technology",
  "MRF": "Automobile & Auto Components",
  "MRPL": "Oil, Gas & Consumable Fuels",
  "MSTCLTD": "Services (Logistics/Transportation/Aviation)",
  "MSUMI": "Automobile & Auto Components",
  "MTARTECH": "Capital Goods",
  "MUTHOOTFIN": "NBFC",
  "NAM-INDIA": "Capital Markets (Broking/AMC/Exchanges)",
  "NATCOPHARM": "Pharmaceuticals",
  "NATIONALUM": "Metals & Mining",
  "NAUKRI": "Consumer Services",
  "NAVA": "Power",
  "NAVINFLUOR": "Chemicals",
  "NAZARA": "Media, Entertainment & Publication",
  "NBCC": "Construction",
  "NCC": "Construction",
  "NEOGEN": "Chemicals",
  "NESCO": "Services (Logistics/Transportation/Aviation)",
  "NESTLEIND": "Fast Moving Consumer Goods (FMCG)",
  "NETWEB": "Information Technology",
  "NETWORK18": "Media, Entertainment & Publication",
  "NEULANDLAB": "Pharmaceuticals",
  "NEWGEN": "Information Technology",
  "NFL": "Chemicals",
  "NH": "Pharmaceuticals",
  "NHPC": "Power",
  "NIACL": "NBFC",
  "NIVABUPA": "Insurance",
  "NLCINDIA": "Power",
  "NMDC": "Metals & Mining",
  "NSLNISP": "Metals & Mining",
  "NTPC": "Power",
  "NTPCGREEN": "Power",
  "NUVAMA": "Capital Markets (Broking/AMC/Exchanges)",
  "NUVOCO": "Construction Materials (Cement)",
  "NYKAA": "Consumer Services",
  "OBEROIRLTY": "Realty",
  "OFSS": "Information Technology",
  "OIL": "Oil, Gas & Consumable Fuels",
  "OLAELEC": "Automobile & Auto Components",
  "OLECTRA": "Automobile & Auto Components",
  "ONESOURCE": "Pharmaceuticals",
  "ONGC": "Oil, Gas & Consumable Fuels",
  "OPTIEMUS": "Telecommunication",
  "ORIENTCEM": "Construction Materials (Cement)",
  "ORKLAINDIA": "Fast Moving Consumer Goods (FMCG)",
  "OSWALPUMPS": "Capital Goods",
  "PAGEIND": "Textiles",
  "PARADEEP": "Chemicals",
  "PARAS": "Capital Goods",
  "PARKHOSPS": "Pharmaceuticals",
  "PATANJALI": "Fast Moving Consumer Goods (FMCG)",
  "PAYTM": "NBFC",
  "PCBL": "Chemicals",
  "PCJEWELLER": "Consumer Durables",
  "PERSISTENT": "Information Technology",
  "PETRONET": "Oil, Gas & Consumable Fuels",
  "PFC": "NBFC",
  "PFIZER": "Pharmaceuticals",
  "PFOCUS": "Media, Entertainment & Publication",
  "PGEL": "Consumer Durables",
  "PGIL": "Textiles",
  "PHOENIXLTD": "Realty",
  "PICCADIL": "Fast Moving Consumer Goods (FMCG)",
  "PIDILITIND": "Chemicals",
  "PIIND": "Chemicals",
  "PINELABS": "NBFC",
  "PIRAMALFIN": "NBFC",
  "PNB": "Banks",
  "PNBHOUSING": "NBFC",
  "PNCINFRA": "Construction",
  "PNGJL": "Consumer Durables",
  "POLICYBZR": "NBFC",
  "POLYCAB": "Capital Goods",
  "POLYMED": "Pharmaceuticals",
  "POONAWALLA": "NBFC",
  "POWERGRID": "Power",
  "POWERINDIA": "Capital Goods",
  "POWERMECH": "Construction",
  "PPLPHARMA": "Pharmaceuticals",
  "PRAJIND": "Capital Goods",
  "PREMIERENE": "Capital Goods",
  "PRESTIGE": "Realty",
  "PRICOLLTD": "Automobile & Auto Components",
  "PRIVISCL": "Chemicals",
  "PRSMJOHNSN": "Construction Materials (Cement)",
  "PRUDENT": "NBFC",
  "PTC": "Power",
  "PTCIL": "Capital Goods",
  "PURVA": "Realty",
  "PVRINOX": "Media, Entertainment & Publication",
  "PWL": "Consumer Services",
  "QPOWER": "Capital Goods",
  "QUESS": "Services (Logistics/Transportation/Aviation)",
  "RADICO": "Fast Moving Consumer Goods (FMCG)",
  "RAILTEL": "Telecommunication",
  "RAIN": "Chemicals",
  "RAINBOW": "Pharmaceuticals",
  "RALLIS": "Chemicals",
  "RAMCOCEM": "Construction Materials (Cement)",
  "RATEGAIN": "Information Technology",
  "RATNAMANI": "Capital Goods",
  "RAYMONDLSL": "Textiles",
  "RBA": "Consumer Services",
  "RBLBANK": "Banks",
  "RCF": "Chemicals",
  "RECLTD": "NBFC",
  "REDINGTON": "Services (Logistics/Transportation/Aviation)",
  "REDTAPE": "Consumer Durables",
  "REFEX": "Capital Goods",
  "RELAXO": "Consumer Durables",
  "RELIANCE": "Oil, Gas & Consumable Fuels",
  "RELIGARE": "NBFC",
  "RENUKA": "Fast Moving Consumer Goods (FMCG)",
  "RHIM": "Capital Goods",
  "RITES": "Construction",
  "RKFORGE": "Automobile & Auto Components",
  "ROUTE": "Telecommunication",
  "RPOWER": "Power",
  "RRKABEL": "Capital Goods",
  "RTNINDIA": "Consumer Services",
  "RTNPOWER": "Power",
  "RUBICON": "Pharmaceuticals",
  "RVNL": "Construction",
  "SAATVIKGL": "Capital Goods",
  "SAFARI": "Consumer Durables",
  "SAGILITY": "Information Technology",
  "SAIL": "Metals & Mining",
  "SAILIFE": "Pharmaceuticals",
  "SAMHI": "Consumer Services",
  "SAMMAANCAP": "NBFC",
  "SANDUMA": "Metals & Mining",
  "SANOFICONR": "Healthcare Services (Hospitals/Diagnostics)",
  "SANSERA": "Automobile & Auto Components",
  "SAPPHIRE": "Consumer Services",
  "SARDAEN": "Metals & Mining",
  "SAREGAMA": "Media, Entertainment & Publication",
  "SBFC": "NBFC",
  "SBICARD": "NBFC",
  "SBILIFE": "Insurance",
  "SBIN": "Banks",
  "SCHAEFFLER": "Automobile & Auto Components",
  "SCHNEIDER": "Capital Goods",
  "SCI": "Services (Logistics/Transportation/Aviation)",
  "SENCO": "Consumer Durables",
  "SFL": "Consumer Durables",
  "SHAILY": "Consumer Durables",
  "SHAKTIPUMP": "Capital Goods",
  "SHARDACROP": "Chemicals",
  "SHAREINDIA": "NBFC",
  "SHILPAMED": "Pharmaceuticals",
  "SHREECEM": "Construction Materials (Cement)",
  "SHRIPISTON": "Automobile & Auto Components",
  "SHRIRAMFIN": "NBFC",
  "SHYAMMETL": "Capital Goods",
  "SIEMENS": "Capital Goods",
  "SIGNATURE": "Realty",
  "SJVN": "Power",
  "SKFINDIA": "Automobile & Auto Components",
  "SKFINDUS": "Capital Goods",
  "SKIPPER": "Capital Goods",
  "SKYGOLD": "Consumer Durables",
  "SMARTWORKS": "Services (Logistics/Transportation/Aviation)",
  "SMLMAH": "Capital Goods",
  "SOBHA": "Realty",
  "SOLARINDS": "Chemicals",
  "SONACOMS": "Automobile & Auto Components",
  "SONATSOFTW": "Information Technology",
  "SOUTHBANK": "Banks",
  "SPARC": "Pharmaceuticals",
  "SPLPETRO": "Chemicals",
  "SRF": "Chemicals",
  "STAR": "Pharmaceuticals",
  "STARCEMENT": "Construction Materials (Cement)",
  "STARHEALTH": "Insurance",
  "STLTECH": "Telecommunication",
  "STYL": "NBFC",
  "STYRENIX": "Chemicals",
  "SUBROS": "Capital Goods",
  "SUDARSCHEM": "Chemicals",
  "SUDEEPPHRM": "Chemicals",
  "SUMICHEM": "Chemicals",
  "SUNDARMFIN": "NBFC",
  "SUNPHARMA": "Pharmaceuticals",
  "SUNTECK": "Realty",
  "SUNTV": "Media, Entertainment & Publication",
  "SUPREMEIND": "Capital Goods",
  "SUPRIYA": "Pharmaceuticals",
  "SURYAROSNI": "Capital Goods",
  "SUZLON": "Capital Goods",
  "SWANCORP": "Chemicals",
  "SWIGGY": "Consumer Services",
  "SWSOLAR": "Construction",
  "SYNGENE": "Pharmaceuticals",
  "SYRMA": "Capital Goods",
  "TANLA": "Information Technology",
  "TARC": "Realty",
  "TARIL": "Capital Goods",
  "TATACAP": "NBFC",
  "TATACHEM": "Chemicals",
  "TATACOMM": "Telecommunication",
  "TATACONSUM": "Fast Moving Consumer Goods (FMCG)",
  "TATAELXSI": "Information Technology",
  "TATAINVEST": "NBFC",
  "TATAPOWER": "Power",
  "TATASTEEL": "Metals & Mining",
  "TATATECH": "Information Technology",
  "TBOTEK": "Consumer Services",
  "TCS": "Information Technology",
  "TDPOWERSYS": "Capital Goods",
  "TECHM": "Information Technology",
  "TECHNOE": "Construction",
  "TEGA": "Capital Goods",
  "TEJASNET": "Telecommunication",
  "TENNIND": "Automobile & Auto Components",
  "TEXRAIL": "Capital Goods",
  "THANGAMAYL": "Consumer Durables",
  "THELEELA": "Consumer Services",
  "THERMAX": "Capital Goods",
  "THOMASCOOK": "Consumer Services",
  "THYROCARE": "Pharmaceuticals",
  "TI": "Fast Moving Consumer Goods (FMCG)",
  "TIINDIA": "Automobile & Auto Components",
  "TIMETECHNO": "Capital Goods",
  "TIMKEN": "Capital Goods",
  "TIPSMUSIC": "Media, Entertainment & Publication",
  "TITAGARH": "Capital Goods",
  "TITAN": "Consumer Durables",
  "TMB": "Banks",
  "TMCV": "Capital Goods",
  "TMPV": "Automobile & Auto Components",
  "TORNTPHARM": "Pharmaceuticals",
  "TORNTPOWER": "Power",
  "TRANSRAILL": "Capital Goods",
  "TRAVELFOOD": "Consumer Services",
  "TRENT": "Consumer Services",
  "TRIDENT": "Textiles",
  "TRITURBINE": "Capital Goods",
  "TRIVENI": "Fast Moving Consumer Goods (FMCG)",
  "TSFINV": "NBFC",
  "TTML": "Telecommunication",
  "TVSMOTOR": "Automobile & Auto Components",
  "TVSSCS": "Services (Logistics/Transportation/Aviation)",
  "UBL": "Fast Moving Consumer Goods (FMCG)",
  "UCOBANK": "Banks",
  "UJJIVANSFB": "Banks",
  "ULTRACEMCO": "Construction Materials (Cement)",
  "UNIONBANK": "Banks",
  "UNITDSPR": "Fast Moving Consumer Goods (FMCG)",
  "UNOMINDA": "Automobile & Auto Components",
  "UPL": "Chemicals",
  "URBANCO": "Consumer Services",
  "USHAMART": "Capital Goods",
  "UTIAMC": "Capital Markets (Broking/AMC/Exchanges)",
  "UTLSOLAR": "Capital Goods",
  "V2RETAIL": "Consumer Services",
  "VAIBHAVGBL": "Consumer Durables",
  "VARROC": "Automobile & Auto Components",
  "VBL": "Fast Moving Consumer Goods (FMCG)",
  "VEDL": "Metals & Mining",
  "VGUARD": "Consumer Durables",
  "VIJAYA": "Healthcare Services (Hospitals/Diagnostics)",
  "VIKRAMSOLR": "Capital Goods",
  "VIPIND": "Consumer Durables",
  "VIYASH": "Pharmaceuticals",
  "VMART": "Consumer Services",
  "VMM": "Consumer Services",
  "VOLTAMP": "Capital Goods",
  "VOLTAS": "Consumer Durables",
  "VTL": "Textiles",
  "WAAREEENER": "Capital Goods",
  "WAAREERTL": "Capital Goods",
  "WABAG": "Capital Goods",
  "WAKEFIT": "Consumer Durables",
  "WEBELSOLAR": "Capital Goods",
  "WELCORP": "Capital Goods",
  "WELENT": "Construction",
  "WELSPUNLIV": "Textiles",
  "WESTLIFE": "Consumer Services",
  "WEWORK": "Services (Logistics/Transportation/Aviation)",
  "WHIRLPOOL": "Consumer Durables",
  "WIPRO": "Information Technology",
  "WOCKPHARMA": "Pharmaceuticals",
  "YATHARTH": "Healthcare Services (Hospitals/Diagnostics)",
  "YESBANK": "Banks",
  "ZAGGLE": "Information Technology",
  "ZEEL": "Media, Entertainment & Publication",
  "ZENSARTECH": "Information Technology",
  "ZENTEC": "Capital Goods",
  "ZFCVINDIA": "Automobile & Auto Components",
  "ZYDUSLIFE": "Pharmaceuticals",
  "ZYDUSWELL": "Fast Moving Consumer Goods (FMCG)"
};

/** Verbatim NSE-sourced sector for a symbol (e.g. "LT", "TCS") — the
 * authoritative lookup, tried BEFORE the AI-guess/peer-group fallback in
 * normalizeSectorLabel(). Returns null if this symbol isn't in the Nifty
 * Total Market universe. */
export function getNseSector(symbol) {
  if (!symbol) return null;
  return NSE_SECTOR_BY_SYMBOL[symbol.trim().toUpperCase()] || null;
}
